### ISSUE TITLE
关于对齐方式的实现

### ISSUE THREAD

**Issue by BetterLive** [jiliuliu/SIXRichEditor#2]
请教，如何实现多行输入时，每一行有不同的对齐方式，比如第一行居中，第二行居左，第三居右等

**Comment by SixLiam** [comment]
项目里并没有实现这个功能，但我尝试了下，通过设置每行的NSMutableParagraphStyle.alignment就可以实现。同时还发现了问题，只有当选中一行中的全部文字时才有用。我的测试代码如下：
- (void)setTextAlignmentInRange {
    NSRange range = self.selectedRange;
    NSDictionary *dict = [self.attributedText attributesAtIndex:self.selectedRange.location effectiveRange:&range];
    NSParagraphStyle *style = dict[NSParagraphStyleAttributeName];
    
    NSMutableParagraphStyle *mStyle = style.mutableCopy;
    mStyle.alignment = self->six_textAlignment;
    NSMutableAttributedString *attributedString = self.attributedText.mutableCopy;
    [attributedString addAttribute:NSParagraphStyleAttributeName value:mStyle range:self.selectedRange];
    self.attributedText = attributedString.copy;
}

**Comment by BetterLive** [comment]
好的，多谢提供思路
